// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	cart "e-commerce/features/cart"

	mock "github.com/stretchr/testify/mock"
)

// CartData is an autogenerated mock type for the CartData type
type CartData struct {
	mock.Mock
}

// AddCHPData provides a mock function with given fields: cartID, newCart
func (_m *CartData) AddCHPData(cartID uint, newCart cart.Core) (cart.Core, error) {
	ret := _m.Called(cartID, newCart)

	var r0 cart.Core
	if rf, ok := ret.Get(0).(func(uint, cart.Core) cart.Core); ok {
		r0 = rf(cartID, newCart)
	} else {
		r0 = ret.Get(0).(cart.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, cart.Core) error); ok {
		r1 = rf(cartID, newCart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddCartData provides a mock function with given fields: newCart
func (_m *CartData) AddCartData(newCart cart.Core) (cart.Core, error) {
	ret := _m.Called(newCart)

	var r0 cart.Core
	if rf, ok := ret.Get(0).(func(cart.Core) cart.Core); ok {
		r0 = rf(newCart)
	} else {
		r0 = ret.Get(0).(cart.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(cart.Core) error); ok {
		r1 = rf(newCart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCartData provides a mock function with given fields: userID, cartID
func (_m *CartData) DeleteCartData(userID uint, cartID uint) error {
	ret := _m.Called(userID, cartID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(userID, cartID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MyCartData provides a mock function with given fields: id
func (_m *CartData) MyCartData(id uint) ([]cart.Core, error) {
	ret := _m.Called(id)

	var r0 []cart.Core
	if rf, ok := ret.Get(0).(func(uint) []cart.Core); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cart.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCartData provides a mock function with given fields: userID, cartID, updateCart
func (_m *CartData) UpdateCartData(userID uint, cartID uint, updateCart cart.Core) (cart.Core, error) {
	ret := _m.Called(userID, cartID, updateCart)

	var r0 cart.Core
	if rf, ok := ret.Get(0).(func(uint, uint, cart.Core) cart.Core); ok {
		r0 = rf(userID, cartID, updateCart)
	} else {
		r0 = ret.Get(0).(cart.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, uint, cart.Core) error); ok {
		r1 = rf(userID, cartID, updateCart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCartData interface {
	mock.TestingT
	Cleanup(func())
}

// NewCartData creates a new instance of CartData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCartData(t mockConstructorTestingTNewCartData) *CartData {
	mock := &CartData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
