// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	order "e-commerce/features/order"

	mock "github.com/stretchr/testify/mock"
)

// OrderData is an autogenerated mock type for the OrderData type
type OrderData struct {
	mock.Mock
}

// Add provides a mock function with given fields: userID
func (_m *OrderData) Add(userID uint) (order.Core, error) {
	ret := _m.Called(userID)

	var r0 order.Core
	if rf, ok := ret.Get(0).(func(uint) order.Core); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(order.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewOrderData interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderData creates a new instance of OrderData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderData(t mockConstructorTestingTNewOrderData) *OrderData {
	mock := &OrderData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
