// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	order "e-commerce/features/order"

	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// Add provides a mock function with given fields: token, cartID, adrress
func (_m *OrderService) Add(token interface{}, cartID uint, adrress string) (order.Core, error) {
	ret := _m.Called(token, cartID, adrress)

	var r0 order.Core
	if rf, ok := ret.Get(0).(func(interface{}, uint, string) order.Core); ok {
		r0 = rf(token, cartID, adrress)
	} else {
		r0 = ret.Get(0).(order.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, uint, string) error); ok {
		r1 = rf(token, cartID, adrress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderHistory provides a mock function with given fields: token
func (_m *OrderService) OrderHistory(token interface{}) ([]order.Core, error) {
	ret := _m.Called(token)

	var r0 []order.Core
	if rf, ok := ret.Get(0).(func(interface{}) []order.Core); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrderStatus provides a mock function with given fields: token, orderID, updatedStatus
func (_m *OrderService) UpdateOrderStatus(token interface{}, orderID uint, updatedStatus string) error {
	ret := _m.Called(token, orderID, updatedStatus)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uint, string) error); ok {
		r0 = rf(token, orderID, updatedStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewOrderService interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderService(t mockConstructorTestingTNewOrderService) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
